### ISSUE TITLE
Make some code more general

### ISSUE THREAD

**Issue by themperek** [SiLab-Bonn/pyBAR#14]
I have added an iterator on Dut that gives modules.
see: https://github.com/SiLab-Bonn/basil/blob/development/host/tests/test_SimSpi.py#L120

It allows to make this code more general:
https://github.com/SiLab-Bonn/pyBAR/blob/development/pybar/daq/fifo_readout.py#L280

Something like this:

``` python
for  item in self.dut:
    if item.__class__.__name__ is 'fei4_rx':
       item['RX_RESET']
```

**Comment by laborleben** [comment]
thumbs up :-)

**Comment by laborleben** [comment]
this is done.
