### ISSUE TITLE
broken GDAC tuning with GDAC>=255

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR#20]
...reported via pybar-devel.

**Comment by DavidLP** [comment]
The issue is that the bit toggleling during the GDAC tuning takes the VthinAF/VthinAC settings and not a generic set/get GDAC function. Thus the differences between FE-I4A / B are not treated here correctly.

**Comment by laborleben** [comment]
Tested, and working with GDAC > 255.
