### ISSUE TITLE
PUB/SUB sockets are failing when binding/closing at high rates 

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR#31]
PUB/SUB sockets are failing when binding/closing at high rates e.g. HitOrCalibration

**Comment by DavidLP** [comment]
HitOrCalibration has a very low hit rate.

**Comment by laborleben** [comment]
what I meant was the socket bind and close operations

**Comment by DavidLP** [comment]
Ok, hehe :-)

**Comment by laborleben** [comment]
Also I want to note that the PUB/SUB does not work reliable. After some time, closing and opening the PUB socket no data is received by the SUB socket. The bind (PUB) and connect (SUB) seems to work.

Therefore I recommend going back to PUSH/PULL pattern (wich is bad for distributing data along monitor and storage) or use another distribution system.

**Comment by DavidLP** [comment]
I have not seen an issue with PUB/SUB yet. It does not have to work reliable. So what is the specific problem?

**Comment by laborleben** [comment]
no further information provided, closing the ticket
