### ISSUE TITLE
Occupancy of analog scan gives values between 99 and 100. 

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR#45]
Expected: 100

I do not know, if other scans are affected (threshold scan). Usually the first injection after shifting the mask fails.

**Comment by DavidLP** [comment]
Really? I have checked this several times. Do you suspect a change that introduced this?

**Comment by DavidLP** [comment]
Actually when I use an external pulser I do the first injection to be not recorded ... Weird.

**Comment by laborleben** [comment]
That is indeed weird. Maybe more delay necessary or an bug in the silicon.

**Comment by DavidLP** [comment]
I checked. All hits are there in analog scan. I close this issue, since it must be the chip and seems to be unrelated to a code change.
