### ISSUE TITLE
Occupancy plot to pdf

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/pyBAR#57]
When I use `mask_step: 3` and  `enable_mask_steps: [1]` I get the following result plot:

![capture](https://cloud.githubusercontent.com/assets/6951141/17709274/bdbd3b56-63e8-11e6-8e9c-03c8676c67b9.JPG)

How does that make sence?

**Comment by laborleben** [comment]
this is just displaying the moiré effect? Can you confirm with the binary mask?

**Comment by DavidLP** [comment]
Maybe. But I think that was working once.

**Comment by DavidLP** [comment]
The mask is correct. It is really just this plot. The larger plot looks also better.

**Comment by laborleben** [comment]
https://github.com/matplotlib/matplotlib/issues/2972

This is explaining it.

**Comment by DavidLP** [comment]
I do not see how that explains anything, since I do not see a blur.

**Comment by laborleben** [comment]
As it is now in development, the full resolution is displayed (interpolation="none"). So every pixel is displayed when zooming in. There are effects with some PDF viewers which interpolate when zooming out (the PDF looks like interpolation="nearest").

**Comment by DavidLP** [comment]
When I zoom in it looks the same. It is not an interpolation issue when I zoom out ?!

**Comment by laborleben** [comment]
The explanation is, that with interpolation="nearest" and using the PDF backend the resolution is reduced which leads to the observed behavior. Yesterday, I changed the "nearest" to "none" and now you are able to see every pixel (when zooming in, at least under Ubuntu with default PDF viewer).

**Comment by DavidLP** [comment]
Ahh ok, thanks.
