### ISSUE TITLE
Treat PlsrDAC ringing

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/pyBAR#58]
Some FE-I4 (especially after irradiation) show a ringing PlsrDAC:

![jleiaejoepodklhe](https://cloud.githubusercontent.com/assets/6951141/17884616/91d1f99c-6919-11e6-8c66-5433f1a32afe.png)

 If the injection loop is too quick the injected charge can change leading to measured higher noise and a charge that depends on the injection speed. We should add an additional injection delay with std. value = 0 to all scans using the PlsrDAC to be able to make the injecion speed slower.

**Comment by laborleben** [comment]
In the picture there is no ringing before the pulse. Can you explain?

**Comment by laborleben** [comment]
OK, I try to explain: The standard delay is around 80us and the next pulse would be still inside the dangerous region (10us/dev). So this plot either show the first pulse or injections with already extended delay.

**Comment by DavidLP** [comment]
Yes, long delay. I misscalculated. We can have 400 us injection delay with our current FPGA cmd sequenzer implementation (16000 \* 25 ns). That is sufficient. So we just have to add a parameter in software.

**Comment by DavidLP** [comment]
Just to make it clear how the analog scan (and thus all other scans) with std. settings (3rd mask) looks like:
![capture](https://cloud.githubusercontent.com/assets/6951141/17885523/e49ec836-691d-11e6-9d4a-84b0c6cdccac.JPG)

**Comment by DavidLP** [comment]
The ringing can be fixed by increasing the OP amp bias of the:

**IV converter op amp**

![capture](https://cloud.githubusercontent.com/assets/6951141/17886583/c610bd3e-6922-11e6-81c7-a8871a354c8b.JPG)

responsible for the slow return to baseline.

The configuration for a not ringing PlsrDAC is: `PlsrVgOpAmp = 150`

Disclamer: I think `PlsrVgOpAmp` is this OP amps bias. There is also another gain 2 OP amp to increase the rail-to-rail amplitude. It is not mentioned anywhere (?), neither in schematics nor the manual wich op amp is adressed by `PlsrVgOpAmp`. So the explanation is an educated guess.

**Comment by DavidLP** [comment]
Since that does not have to be fixed in software I close this issue.
