### ISSUE TITLE
PlsrDAC injections too fast so that previous pulse does not return to baseline

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR#59]
The left side (before the pulse) is _NOT_ flat.

With default delay (see [here](https://github.com/SiLab-Bonn/pyBAR/blob/31aa34842b1b755e43b9f646426e191bcbda410a/pybar/fei4/register_utils.py#L1267)):

<img width="695" alt="bildschirmfoto 2016-08-30 um 13 21 37" src="https://cloud.githubusercontent.com/assets/8696773/18090050/3fab6b8a-6ec3-11e6-8828-7471996c36c6.png">

With increased delay (+1000 clock cycles):
<img width="679" alt="bildschirmfoto 2016-08-30 um 13 22 48" src="https://cloud.githubusercontent.com/assets/8696773/18090064/4c2dda5a-6ec3-11e6-908e-55895fa6eb53.png">

**Comment by laborleben** [comment]
The good thing is that the HitOR Calibration uses a fixed delay of 5000 which already includes a safety margin.

This is also related:
https://github.com/SiLab-Bonn/pyBAR/commit/f0ba0189406511cda2276ef99e4f46c0c6858d9c
https://github.com/SiLab-Bonn/pyBAR/commit/b1e3fed207b7c8583b93c86ca319ac3fc5b2c5f9
https://github.com/SiLab-Bonn/pyBAR/commit/dd8f7cf7dcc13efdeacce86b86efa0ec16ab4d3f

**Comment by laborleben** [comment]
Reflection?

<img width="921" alt="bildschirmfoto 2016-08-30 um 16 06 51" src="https://cloud.githubusercontent.com/assets/8696773/18092229/cfcbd0f8-6ecb-11e6-8bc3-61cfbc16166d.png">

**Comment by DavidLP** [comment]
Yes I figured it is needed but did not investigate why :-[

**Comment by DavidLP** [comment]
Hehe no. That is crap and no reflection. Does it get better when you change PsrDAC bias? Are you sure that you do not average over different Pulses. Does a single pulse look like this too?

**Comment by DavidLP** [comment]
BTW: I never saw this for chips between 60 - 840 MRad. FE-I4 A and B.

**Comment by laborleben** [comment]
I get this bump also with cables of different length, grounding and cables types. This is probably a bad timing in the FE. Increasing the delay (repetition speed) in the FPGA removes this bump.

+20 Clocks:
<img width="672" alt="bildschirmfoto 2016-08-30 um 16 48 23" src="https://cloud.githubusercontent.com/assets/8696773/18093838/9819e46e-6ed1-11e6-81d0-839b4f52bfb7.png">

+60 Clocks:
<img width="902" alt="bildschirmfoto 2016-08-30 um 16 44 47" src="https://cloud.githubusercontent.com/assets/8696773/18093762/54e959c2-6ed1-11e6-8897-f0dc69643e15.png">

+100 Clocks:
<img width="914" alt="bildschirmfoto 2016-08-30 um 16 45 51" src="https://cloud.githubusercontent.com/assets/8696773/18093739/39d95f42-6ed1-11e6-8708-80e76de5852b.png">

**Comment by DavidLP** [comment]
Weird, would be interessting to see the full signal after the injection.

**Comment by laborleben** [comment]
I could draw no conclusion other than this is a FE issue. The bumps are moving, getting smaller or larger depending on the delay and PlsrDAC setting but they are never disappearing.

**Comment by laborleben** [comment]
PlsrVgOpAmp: 255 -> 100
<img width="572" alt="bildschirmfoto 2016-08-31 um 00 12 56" src="https://cloud.githubusercontent.com/assets/8696773/18109105/cb515428-6f0f-11e6-947c-46f88c02fded.png">

**Comment by laborleben** [comment]
OK, found the bug: ist was the averaging over all waveforms, which may include other waveforms than the pulse. Fixing the trigger gives me this nice picture (even though I don't know where the 13.5MHz buzz is coming from, averaging over 512 waveforms!):
<img width="929" alt="bildschirmfoto 2016-08-31 um 01 07 35" src="https://cloud.githubusercontent.com/assets/8696773/18110290/59fe604c-6f17-11e6-9f73-cba9d46db79a.png">

**Comment by laborleben** [comment]
also very interesting the pulse at PlsrDAC=0:
<img width="903" alt="bildschirmfoto 2016-08-31 um 01 17 16" src="https://cloud.githubusercontent.com/assets/8696773/18110502/ae8e4bc6-6f18-11e6-98ee-791d22e5c130.png">

This is equivalent to 650e!

**Comment by themperek** [comment]
Actually one can try one more time to use external    injection. A proper threshold scan for low thresholds may be possible.

**Comment by DavidLP** [comment]
How did you get a measurable signal for PlsrDAC = 0? Can you show the PlsrDAC -Calibration here, especially for low PlsrDACs that we can see if it is a non linearity or just an offset.

**Comment by DavidLP** [comment]
I guess you redued the bandwith, no?

**Comment by laborleben** [comment]
This was just changing from edge trigger to pulse trigger and I require a certain minimum pulse length ( O(length pulser signal) ). One of the main problems is, that averaging can distort your results, e.g. averaging a flat line and the signal of interest, would you notice that?
There are probably many ways to fix that. One is to require a certain pulse length and hope that there is no other signal that can trigger the oscilloscope, or just investigate every single pulse and average later (which would increase data taking time).
I also observed that the oscilloscope only triggers on a small fraction of the pulses, e.g. from 512 injections into the FE only ~100 samples were taken by the oscilloscope, even after increasing the delay between the pulses.

What I observed is a high linearity of the pulse. The small non-linearity at the lower end comes most likely from the averaging of the small signal with noise.

Plots will follow, I will address the problems described above and update the script in the coming days.

**Comment by DavidLP** [comment]
So summary?: 
- Transfer function is linear + offset
- Trigger on pulse is better for small pulse amplitudes

To your averaging question:
- One should reset the averaging storage before using another PlsrDAC setting. This happens when you switch to single shot mode and then back, at least for the oszis we have. This was to my mind also
  mentioned in the code.

**Comment by DavidLP** [comment]
Since this story has an end I close this issue.
