### ISSUE TITLE
EUDAQ FSM changes in 1.7 and requires change in producers

### ISSUE THREAD

**Issue by arummler** [SiLab-Bonn/pyBAR#62]
https://github.com/eudaq/eudaq/issues/277

Example producer shows necessary changes.

**Comment by laborleben** [comment]
Please use pyBAR https://github.com/SiLab-Bonn/pyBAR/tree/v3.1.2 or 
https://github.com/SiLab-Bonn/pyBAR/tree/v2.2.2 or higher.

Tested in November 2018 during DEPFET test beam at DESY.
