### ISSUE TITLE
tune_fei4 does not work

### ISSUE THREAD

**Issue by thirono** [SiLab-Bonn/pyBAR#64]
The problem can be fixed by reverting to commit f583ddd14edf921fdd22d88de3ad6af672bf6c50.

**Comment by laborleben** [comment]
which tuning does not work? GDAC?

What is the error message?

**Comment by DavidLP** [comment]
GDAC says that always all hits are seen (median = 50) in the _second_ loop step of the tune_fei4 script. And thus converges to GDAC = 255. Running the GDAC stand alone works.
