### ISSUE TITLE
ViTables v2.1 incompatibel with pytables 3.3

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR#66]
The ViTables version v2.1 installed by pyBAR is incompatible with pytables 3.3. The API issues with pytables was fixed in develop branch of PyTables (https://github.com/uvemas/ViTables).

Unfortunately `pip install git+https://github.com/uvemas/ViTables@develop` does not work either, because ViTables throws the following error: `IOError: [Errno 2] No such file or directory: '[...]/miniconda2/lib/python2.7/site-packages/vitables/vtwidgets/rename_dlg.ui'`

Cloning ViTables and installing from sources works:
```
pip uninstall vitables
git clone https://github.com/uvemas/ViTables
git checkout develop
cd ViTables
python setup.py develop
```

**Comment by DavidLP** [comment]
But that is no solution for a setup with Qt5, no?

**Comment by laborleben** [comment]
Not yet tested with Qt5. The solution above is also not satisfying. ViTables just needs more support.

**Comment by DavidLP** [comment]
ViTables is another dead python package. Changing to Qt5 would take a couple of hours.
Internetfame, anybody?

**Comment by DavidLP** [comment]
A work around is to setup a python environment with QT4 for vitables only.

```
conda create -n vitables python=2.7 pyqt=4.11.4 pytables
source activate conda vitables
pip install https://github.com/uvemas/ViTables/archive/v2.1.zip
```

**Comment by laborleben** [comment]
Seems like this is the only viable solution right now.

**Comment by laborleben** [comment]
This was recently fixed in ViTables `master` branch.

Use `python setup.py install` to install vitables.
