### ISSUE TITLE
S Curve fit failed

### ISSUE THREAD

**Issue by lauramari** [SiLab-Bonn/pyBAR#7]
Fast Threshold Scan  aborted;  not enough points to fit S_Curve

Solved by updating; numpy 1.9.0 to numpy 1.9.2 ;Matplotlib 1.4.0 to Matplotlib 1.4.3
and Scipy 0.14.0 to 0.15.1

**Comment by laborleben** [comment]
I'm afraid that more people will run into this. "conda update --all" is needed, I guess.

**Comment by DavidLP** [comment]
Since the solution is already given I close the issue. Is there a way to make this post 'sticky', since the info is important?

**Comment by laborleben** [comment]
good point. Need to be in the documentation since anaconda is not using the latest packages by default.

**Comment by DavidLP** [comment]
Ok I add it to wiki

**Comment by DavidLP** [comment]
Well, actually Ill not add it to the wiki. It is anaconda related. We use miniconda now, that should use the latest packages, I guess. Needs cross check though...
