### ISSUE TITLE
Analysis fails with raw data interpreter 1.3

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/pyBAR#76]
Use `pyBAR development` and `the pyBAR_fei4_interpreter` version 1.3 run the unit tests and see it fail.

**Comment by laborleben** [comment]
Temporary fix: use development version 1.3.1.dev0.

**Comment by laborleben** [comment]
The issues are all solved in all major branches: `master`, `development`, and `v2.2.x`.

Just follow the instructions.
