### ISSUE TITLE
TDC analysis fails, wrong dtype

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR#80]
Affecting https://github.com/SiLab-Bonn/pyBAR/blob/5a3009c72d58ace582d198b17bc628f8ab50599d/pybar/scans/analyze_source_scan_tdc_data.py#L102.

See https://github.com/scipy/scipy/issues/7273 for in-depth bug report.

I leave this open until scipy fixed the issue themselves. In the meantime, the bug can be solved by forcing the x parameter dtype to `np.float64`.

**Comment by DavidLP** [comment]
Yea that is pretty annoying. Had to change it in a lot of places, since I heavily use interpolation everywhere... For me it was fine to do `np.float` wich should automatically use the correct number of bytes according to pc architecture.

**Comment by laborleben** [comment]
Please update scipy to 19.1.
